### ISSUE TITLE
The Epoch for Training the gennerator ?

### ISSUE THREAD

**Issue by kinredon** [SCUT-AILab/CPGA#2]
I noted that the `self.generator_epoch` is set to 0 in the file `train_visda.py` . Thus what is the proper value for training the gennerator?

**Comment by zxr177** [comment]
Hello, I am reproducing this project recently. May I ask if you have reproduced successfully? I encountered some minor problems when reproducing

**Comment by kinredon** [comment]
@zxr177 I do not reproduce this project due to it lacks important implement details as I issued.

**Comment by zxr177** [comment]
Okay, thank you. I also encountered many problems. I got stuck at one point recently. I doubt that no one can reproduce it successfully, except for themselves.

**Comment by qiuzhen8484** [comment]
We have updated the code to solve the mentioned problems.
Thanks for your attention.
