### ISSUE TITLE
數據集

### ISSUE THREAD

**Issue by Lorraine-Kwok** [SCUT-AILab/CPGA#5]
你好！請問如果是別的數據集比如office-31等，該怎麼得到對應pkl文件呢？

**Comment by qiuzhen8484** [comment]
https://github.com/SCUT-AILab/CPGA/blob/4412e1a9b996b1cb0a1ba4dec6c968f7b447d113/dataset.py#L97 This dataset class is used for Office-31. You can create a '.pkl'  file for office-31 with the format {'tran_list': [(file1, label1), (file2, label2), ..], 'val_list': [(file1, label1), (file2, label2), ..]}.

**Comment by Lorraine-Kwok** [comment]
感谢您的回复，令我这个新手能够进行别的数据集训练，叨扰您了
